### PR TITLE
Add NETBEANS-3296 link about Javadoc and Sources

### PR DESCRIPTION
**Pull request by jgneff**
Add a link to the NetBeans bug report NETBEANS-3296, "Attaching JavaFX
Javadoc and Sources." This commit can help make people aware of issues
such as #44 and some possible ways to work around them.

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
Hi @jgneff ,

Can you move the text inside `<div class="alert alert-warning">text</div>` ?

**Comment by jgneff** [comment]
Thanks, @abhinayagarwal. Please let me know if you would like any other changes, and also if you want me to squash my two commits into just one.

**Comment by abhinayagarwal** [comment]
I missed merging this PR :)

@jgneff does this still hold good? I can see that the Netbeans issue is still unresolved.

**Comment by jgneff** [comment]
Thanks, Abhinay. Yes, I think the note is still relevant and helpful. There has been some progress. The following two sub-tasks of the bug report are fixed:

* [NETBEANS-1396](https://issues.apache.org/jira/browse/NETBEANS-1396) - Maven: Downloaded javadoc / sources not attached to artifact with classifier
* [NETBEANS-3303](https://issues.apache.org/jira/browse/NETBEANS-3303) - Modular Gradle project fails to recognize Javadoc and Sources

I think the other six sub-tasks of the bug report still occur. For example, I still have to use the work-around to get the Javadoc and Sources recognized in a project using Apache Ant.

**Pull request merged**
